### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by FoxMcTag** [alta762/gestion-reservation-hotel-en-ligne#1]
Pour le moment à l'éxec je me retrouve avec un CNFE, et dans sa stacktrace je remonte directement chez Oracle sans passer par chez nous.

Suis-je le seul?

**Comment by pasterp** [comment]
RT si t'es triste et installe le driver sql ;)

**Comment by FoxMcTag** [comment]
c'est passé: inta' Fx bancale: peut refactor au propre maintenant
